"""remove_foreign_key_usage_table

Revision ID: 51f00e0e9a67
Revises: 551b2920b23c
Create Date: 2025-12-19 15:55:56.939193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51f00e0e9a67'
down_revision: Union[str, None] = '551b2920b23c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_provider_id'), table_name='usage')
    op.drop_index(op.f('ix_usage_router_id'), table_name='usage')
    op.drop_index(op.f('ix_usage_token_id'), table_name='usage')
    op.drop_constraint(op.f('usage_router_id_fkey'), 'usage', type_='foreignkey')
    op.drop_constraint(op.f('usage_token_id_fkey'), 'usage', type_='foreignkey')
    op.drop_constraint(op.f('usage_provider_id_fkey'), 'usage', type_='foreignkey')
    op.drop_column('usage', 'token_id')
    op.drop_column('usage', 'provider_id')
    op.drop_column('usage', 'router_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usage', sa.Column('router_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('usage', sa.Column('provider_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('usage', sa.Column('token_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('usage_provider_id_fkey'), 'usage', 'provider', ['provider_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('usage_token_id_fkey'), 'usage', 'token', ['token_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('usage_router_id_fkey'), 'usage', 'router', ['router_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_usage_token_id'), 'usage', ['token_id'], unique=False)
    op.create_index(op.f('ix_usage_router_id'), 'usage', ['router_id'], unique=False)
    op.create_index(op.f('ix_usage_provider_id'), 'usage', ['provider_id'], unique=False)
    # ### end Alembic commands ###
