"""add observability usage metrics

Revision ID: 4d42cbcaecff
Revises: a1b2c3d4e5f6
Create Date: 2025-10-10 18:07:04.136365

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4d42cbcaecff"
down_revision: Union[str, None] = "a1b2c3d4e5f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
<<<<<<< HEAD
    op.add_column("usage", sa.Column("get_client_duration", sa.Integer(), nullable=True))
    op.add_column("usage", sa.Column("requeue_count", sa.Integer(), nullable=True))
    op.add_column("usage", sa.Column("client_url", sa.String(), nullable=False))
    op.add_column("usage", sa.Column("strategy", sa.String(), nullable=False))
    op.add_column("usage", sa.Column("policy", sa.String(), nullable=True))
=======
    op.add_column("usage", sa.Column("get_client_duration", sa.Float(), nullable=True))
    op.add_column("usage", sa.Column("requeue_count", sa.Integer(), nullable=True))
    op.add_column("usage", sa.Column("client_url", sa.String(), nullable=False))
    op.add_column("usage", sa.Column("strategy", sa.String(), nullable=False))
>>>>>>> 10b019a (add new metrics for observability)
    op.add_column("usage", sa.Column("performance_score", sa.Float(), nullable=True))
    op.add_column("usage", sa.Column("current_parallel_requests", sa.Integer(), nullable=False))
    op.add_column("usage", sa.Column("max_parallel_requests", sa.Integer(), nullable=True))
    op.add_column("usage", sa.Column("priority", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("usage", "priority")
    op.drop_column("usage", "max_parallel_requests")
    op.drop_column("usage", "current_parallel_requests")
    op.drop_column("usage", "performance_score")
    op.drop_column("usage", "strategy")
<<<<<<< HEAD
    op.drop_column("usage", "policy")
=======
>>>>>>> 10b019a (add new metrics for observability)
    op.drop_column("usage", "client_url")
    op.drop_column("usage", "requeue_count")
    op.drop_column("usage", "get_client_duration")
    # ### end Alembic commands ###
