"""remove CREATE_PUBLIC_COLLECTION permission

Revision ID: b2d58fce4b3c
Revises: c83449930fe2
Create Date: 2026-08-19 12:39:26.181566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b2d58fce4b3c'
down_revision: Union[str, None] = 'c83449930fe2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_id'), table_name='document')
    op.drop_table('document')
    op.drop_index(op.f('ix_collection_id'), table_name='collection')
    op.drop_table('collection')
    op.drop_column('role', 'storage_limit')
    # ### end Alembic commands ###

    op.execute(
        """
        DELETE FROM permission
        WHERE permission::text IN ('CREATE_PUBLIC_COLLECTION', 'create_public_collection')
        """
    )
    op.execute("ALTER TABLE permission ALTER COLUMN permission TYPE text USING permission::text;")
    op.execute("DROP TYPE IF EXISTS permissiontype;")
    op.execute("CREATE TYPE permissiontype AS ENUM ('ADMIN', 'READ_METRIC', 'PROVIDE_MODELS');")
    op.execute("ALTER TABLE permission ALTER COLUMN permission TYPE permissiontype USING permission::permissiontype;")


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("ALTER TABLE permission ALTER COLUMN permission TYPE text USING permission::text;")
    op.execute("DROP TYPE IF EXISTS permissiontype;")
    op.execute("CREATE TYPE permissiontype AS ENUM ('ADMIN', 'CREATE_PUBLIC_COLLECTION', 'READ_METRIC', 'PROVIDE_MODELS');")
    op.execute("ALTER TABLE permission ALTER COLUMN permission TYPE permissiontype USING permission::permissiontype;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('storage_limit', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_table('collection',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('visibility', postgresql.ENUM('PRIVATE', 'PUBLIC', name='collectionvisibility'), autoincrement=False, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('collection_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('collection_pkey'))
    )
    op.create_index(op.f('ix_collection_id'), 'collection', ['id'], unique=False)
    op.create_table('document',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('collection_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('size', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], name=op.f('document_collection_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('document_pkey'))
    )
    op.create_index(op.f('ix_document_id'), 'document', ['id'], unique=False)
    # ### end Alembic commands ###
