"""add basic auth to provider definition

Revision ID: 0daf52aadaf0
Revises: 7498a3a48271
Create Date: 2026-06-10 18:28:42.580559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0daf52aadaf0'
down_revision: Union[str, None] = '7498a3a48271'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider', sa.Column('basic_auth', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('provider', 'basic_auth')
    # ### end Alembic commands ###
