"""add is_default property and partial unique constraint on is_default property for models

Revision ID: 4ad3859d4c64
Revises: f02a2525b97c
Create Date: 2026-02-02 22:04:55.231167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import logging


# revision identifiers, used by Alembic.
revision: str = '4ad3859d4c64'
down_revision: Union[str, None] = 'f02a2525b97c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
logger = logging.getLogger(__name__)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    logger.warning("Upgrade: adding 'is_default' column to 'router' with server_default=FALSE for existing rows")
    op.add_column(
        'router',
        sa.Column('is_default', sa.Boolean(), nullable=False, server_default=sa.text('FALSE')),
    )
    logger.warning("Upgrade: creating partial unique index 'unique_default_per_model_type' on 'router(type)' where is_default IS TRUE")
    op.create_index(
        'unique_default_per_model_type',
        'router',
        ['type'],
        unique=True,
        postgresql_where=sa.text('is_default IS TRUE'),
    )
    logger.warning("Upgrade: finished")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    logger.warning("Downgrade: dropping partial unique index 'unique_default_per_model_type'")
    op.drop_index('unique_default_per_model_type', table_name='router', postgresql_where=sa.text('is_default IS TRUE'))
    logger.warning("Downgrade: dropping column 'is_default' from 'router'")
    op.drop_column('router', 'is_default')
    logger.warning("Downgrade: finished")
    # ### end Alembic commands ###