"""update constraint name

Revision ID: c83449930fe2
Revises: 50ddc08e9202
Create Date: 2026-07-30 18:05:03.612870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c83449930fe2'
down_revision: Union[str, None] = '50ddc08e9202'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('unique_user_email_sub_iss'), 'user', type_='unique')
    op.create_unique_constraint('unique_user_sub_iss', 'user', ['sub', 'iss'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_sub_iss', 'user', type_='unique')
    op.create_unique_constraint(op.f('unique_user_email_sub_iss'), 'user', ['sub', 'iss'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
