"""add constraint on router delete

Revision ID: 9fd5b6491d48
Revises: 4a8f3b3aed3a
Create Date: 2026-05-06 12:24:07.238199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fd5b6491d48'
down_revision: Union[str, None] = '4a8f3b3aed3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('router_user_id_fkey'), 'router', type_='foreignkey')
    op.create_foreign_key(None, 'router', 'user', ['user_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'router', type_='foreignkey')
    op.create_foreign_key(op.f('router_user_id_fkey'), 'router', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
