"""add sso access

Revision ID: f94a77198389
Revises: 5138304df5f5
Create Date: 2026-06-26 12:57:42.469421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f94a77198389'
down_revision: Union[str, None] = '5138304df5f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sso_policy_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('EMAIL', 'ORGANIZATION', 'ROLE', name='ssoaccessruletype'), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type', 'value', name='unique_sso_policy_type_value')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sso_policy_rule')
    op.execute("DROP TYPE IF EXISTS ssoaccessruletype")
    # ### end Alembic commands ###
