"""add_router_qos_fields and remove basic auth

Revision ID: c8fef686d652
Revises: a9c2e7b41d35
Create Date: 2026-09-22 18:51:51.609524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c8fef686d652'
down_revision: Union[str, None] = 'a9c2e7b41d35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider', sa.Column('qos_limit', sa.Integer(), nullable=True))
    op.drop_column('provider', 'basic_auth')
    op.add_column('router', sa.Column('qos_retries_before_reject', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('router', 'qos_retries_before_reject')
    op.add_column('provider', sa.Column('basic_auth', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('provider', 'qos_limit')
    # ### end Alembic commands ###
