"""add storage limits

Revision ID: 7498a3a48271
Revises: 4cbcc969c660
Create Date: 2026-06-01 14:21:30.145281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7498a3a48271'
down_revision: Union[str, None] = '4cbcc969c660'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('storage_limit', sa.Integer(), nullable=True))
    op.add_column('document', sa.Column('size', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'storage_limit')
    op.drop_column('document', 'size')
    # ### end Alembic commands ###
