"""add constraint on provinder delete

Revision ID: 4cbcc969c660
Revises: 9fd5b6491d48
Create Date: 2026-05-06 16:58:33.949974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cbcc969c660'
down_revision: Union[str, None] = '9fd5b6491d48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('provider_user_id_fkey'), 'provider', type_='foreignkey')
    op.create_foreign_key(None, 'provider', 'user', ['user_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'provider', type_='foreignkey')
    op.create_foreign_key(op.f('provider_user_id_fkey'), 'provider', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
