"""remove master user

Revision ID: 4a8f3b3aed3a
Revises: c206a2bfefe9
Create Date: 2026-04-23 18:14:31.538526

"""
import logging
from typing import Sequence, Union

from alembic import op
import bcrypt
import sqlalchemy as sa

from api.utils.configuration import configuration


# revision identifiers, used by Alembic.
revision: str = '4a8f3b3aed3a'
down_revision: Union[str, None] = 'c206a2bfefe9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

logger = logging.getLogger(__name__)

DEFAULT_ADMIN_ROLE_NAME = "bootstrap_admin"
DEFAULT_ADMIN_USER_NAME = "bootstrap_admin"


def _get_null_user_reference_count(bind: sa.Connection) -> int:
    provider_null_count = bind.execute(sa.text("SELECT COUNT(*) FROM provider WHERE user_id IS NULL")).scalar_one()
    router_null_count = bind.execute(sa.text("SELECT COUNT(*) FROM router WHERE user_id IS NULL")).scalar_one()
    return provider_null_count + router_null_count


def _ensure_bootstrap_admin(bind: sa.Connection) -> int:
    admin_username = configuration.settings.auth_bootsrap_admin_username
    admin_password = configuration.settings.auth_bootsrap_admin_password
    
    # Create the default admin role
    role_id = bind.execute(
        sa.text(
            """
            INSERT INTO role (name, created, updated)
            VALUES (:name, NOW(), NOW())
            RETURNING id
            """
        ),
        {"name": DEFAULT_ADMIN_ROLE_NAME},
    ).scalar_one()

    # Create the default admin permission
    bind.execute(
        sa.text(
            """
            INSERT INTO permission (role_id, permission, created)
            VALUES (:role_id, CAST(:permission AS permissiontype), NOW())
            """
        ),
        {"role_id": role_id, "permission": "ADMIN"},
    )

    # Create the default admin user
    hashed_password = bcrypt.hashpw(admin_password.encode("utf-8"), bcrypt.gensalt()).decode("utf-8")
    user_id = bind.execute(
        sa.text(
            """
            INSERT INTO "user" (email, password, name, role_id, priority, created, updated)
            VALUES (:email, :password, :name, :role_id, :priority, NOW(), NOW())
            RETURNING id
            """
        ),
        {
            "email": admin_username,
            "password": hashed_password,
            "name": DEFAULT_ADMIN_USER_NAME,
            "role_id": role_id,
            "priority": 0,
        },
    ).scalar_one()

    return user_id


def _backfill_missing_user_references(bind: sa.Connection, user_id: int) -> None:
    bind.execute(
        sa.text("UPDATE provider SET user_id = :user_id WHERE user_id IS NULL"),
        {"user_id": user_id},
    )
    bind.execute(
        sa.text("UPDATE router SET user_id = :user_id WHERE user_id IS NULL"),
        {"user_id": user_id},
    )


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()

    try:
        null_user_reference_count = _get_null_user_reference_count(bind)
        if null_user_reference_count > 0:
            logger.warning(
                f"Found {null_user_reference_count} provider/router rows with NULL user_id, creating or reusing bootstrap admin user for backfill.",
                null_user_reference_count,
            )
            
            admin_user_id = _ensure_bootstrap_admin(bind)
            _backfill_missing_user_references(bind, admin_user_id)

            remaining_null_user_reference_count = _get_null_user_reference_count(bind)
            if remaining_null_user_reference_count > 0:
                raise RuntimeError(
                    f"Backfill failed: {remaining_null_user_reference_count} provider/router rows still have NULL user_id."
                )
            else:
                logger.warning("Backfill completed successfully. Created or reused bootstrap admin user for backfill (user_id: %s)", admin_user_id)

        op.alter_column("provider", "user_id", existing_type=sa.INTEGER(), nullable=False)
        op.alter_column("router", "user_id", existing_type=sa.INTEGER(), nullable=False)
    except Exception:
        logger.exception("Migration %s failed while removing nullable user references.", revision)
        raise


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('router', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('provider', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
