"""add unique constraint on key name

Revision ID: 5138304df5f5
Revises: c3d4e5f6a7b9
Create Date: 2026-06-17 15:18:07.038519

"""
import logging
import secrets
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5138304df5f5'
down_revision: Union[str, None] = 'c3d4e5f6a7b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

logger = logging.getLogger(__name__)


def _deduplicate_token_names(bind: sa.Connection) -> None:
    duplicates = bind.execute(
        sa.text(
            """
            SELECT user_id, name, array_agg(id ORDER BY id) AS token_ids
            FROM token
            WHERE name IS NOT NULL
            GROUP BY user_id, name
            HAVING COUNT(*) > 1
            """
        )
    ).all()

    if not duplicates:
        return

    logger.warning(
        "Found %d duplicate token name(s) per user, adding random suffix to resolve conflicts.",
        len(duplicates),
    )

    for row in duplicates:
        user_id, name, token_ids = row.user_id, row.name, list(row.token_ids)
        for token_id in token_ids[1:]:
            new_name = f"{name}-{secrets.token_hex(4)}"
            bind.execute(
                sa.text("UPDATE token SET name = :new_name WHERE id = :token_id"),
                {"new_name": new_name, "token_id": token_id},
            )
            logger.warning(
                "Renamed token id=%s (user_id=%s) from '%s' to '%s'",
                token_id,
                user_id,
                name,
                new_name,
            )


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    _deduplicate_token_names(bind)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_token_name_per_user', 'token', ['user_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_token_name_per_user', 'token', type_='unique')
    # ### end Alembic commands ###
