name: albert-test
services:
  api:
    build:
      context: ..
      dockerfile: app/Dockerfile
    platform: linux/amd64
    restart: always
    environment:
      - COVERAGE_RCFILE=./app/.coveragerc
      - BRAVE_API_KEY=${BRAVE_API_KEY}
      - ALBERT_API_KEY=${ALBERT_API_KEY}
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
      - QDRANT_HOST=qdrant
      - POSTGRES_PORT=5432
      - REDIS_PORT=6379
      - QDRANT_PORT=6333
      - QDRANT_GRPC_PORT=6334
      - MCP_BRIDGE_HOST=albert-test-mcp-bridge-1
      - MCP_BRIDGE_PORT=9875
      - VCR_ENABLED=true
    ports:
      - 8000:8000
    volumes:
      - ./config.test.yml:/config.yml:ro
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      qdrant:
        condition: service_healthy

  postgres:
    extends:
      file: ../compose.yml
      service: postgres 
    ports: !override
      - 8432:5432

  qdrant:
    extends:
      file: ../compose.yml
      service: qdrant
    ports: !override
      - 8333:6333
      - 8334:6334

  redis:
    extends:
      file: ../compose.yml
      service: redis
    ports: !override
      - 8335:6379

  mcp-bridge:
    extends:
      file: ../compose.yml
      service: mcp-bridge
    ports: !override
      - "9875:8000"

volumes:
  postgres:
  redis:
  qdrant:
