name: albert-test
services:
  api:
    build:
      context: ..
      dockerfile: app/Dockerfile
    platform: linux/amd64
    restart: always
    environment:
      - COVERAGE_RCFILE=./app/.coveragerc
      - BRAVE_API_KEY=${BRAVE_API_KEY}
      - ALBERT_API_KEY=${ALBERT_API_KEY}
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
      - ELASTICSEARCH_HOST=elasticsearch
      - POSTGRES_PORT=5432
      - REDIS_PORT=6379
      - ELASTICSEARCH_PORT=9200
      - MCP_BRIDGE_HOST=albert-test-mcp-bridge-1
      - MCP_BRIDGE_PORT=8000
      - VCR_ENABLED=true
    ports: 
      - 8000:8000
    volumes:
      - ./config.test.yml:/config.yml:ro

    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy

  postgres:
    extends:
      file: ../compose.yml
      service: postgres 
    ports: !override
      - 8432:5432

  elasticsearch:
    extends:
      file: ../compose.yml
      service: elasticsearch
    ports: !override
      - 8337:9200

  redis:
    extends:
      file: ../compose.yml
      service: redis
    ports: !override
      - 8335:6379

  mcp-bridge:
    extends:
      file: ../compose.yml
      service: mcp-bridge
    ports: !override
      - 8336:8000

volumes:
  postgres:
  redis:
  elasticsearch:
