general:
  log_level: DEBUG
  tokenizer: "tiktoken_gpt2"

auth:
  master_key: changeme
  max_token_expiration_days: 365

monitoring:
  postgres:
    enabled: true
  prometheus:
    enabled: true

web_search:
  - type: brave
    model: albert-small
    args:
      api_key: ${BRAVE_API_KEY}
    limited_domains:
        - service-public.fr
        - gouv.fr
        - caf.fr
        - info-retraite.fr
        - ameli.fr
        - elysee.fr
        - wikipedia.org
        - autoritedelaconcurrence.fr
        - assemblee-nationale.fr
        - elysee.fr
        - conseil-etat.fr
        - departements.fr
        - courdecassation.fr
        - lcp.fr
        - senat.fr
        - gouvernement.fr
        - vie-publique.fr
        - elections-legislatives.fr
        - ccomptes.fr
        - conseil-constitutionnel.fr
        - ladocumentationfrancaise.fr
        - franceinfo.fr
        - lefigaro.fr
        - ouest-france.fr
        - lemonde.fr
        - leparisien.fr
        - refugies.info

multi_agents_search:
  model: albert-small

mcp:
  mcp_bridge_url: http://localhost:9000/

databases:
  - type: qdrant
    model: embeddings-small
    args:
      url: http://${QDRANT_HOST}:${QDRANT_PORT}
      api_key: changeme
      prefer_grpc: True
      grpc_port: ${QDRANT_GRPC_PORT}
      timeout: 10

  - type: redis
    args:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: changeme

  - type: sql
    context: api
    args:
      url: postgresql+asyncpg://postgres:changeme@${POSTGRES_HOST}:${POSTGRES_PORT}/api
      echo: False
      pool_size: 5
      max_overflow: 10
      pool_pre_ping: True
      connect_args:
        server_settings:
          statement_timeout: "120s"

models:
  - id: albert-large
    type: image-text-to-text
    owned_by: test
    aliases: ["mistralai/Mistral-Small-3.1-24B-Instruct-2503"]
    clients:
      - model: albert-large
        type: albert
        costs:
          prompt_tokens: 1
          completion_tokens: 3
        carbon:
          total_params: 24
          active_params: 24
          model_zone: FRA
        args:
          api_url: https://albert.api.staging.etalab.gouv.fr
          api_key: ${ALBERT_API_KEY}
          timeout: 120

  - id: albert-small
    type: text-generation
    routing_strategy: round_robin
    aliases: ["meta-llama/Llama-3.1-8B-Instruct"]
    clients:
      - model: albert-small
        type: albert
        costs:
          prompt_tokens: 1
          completion_tokens: 3
        carbon:
          total_params: 8
          active_params: 8
          model_zone: FRA
        args:
          api_url: https://albert.api.staging.etalab.gouv.fr
          api_key: ${ALBERT_API_KEY}
          timeout: 120
      - model: albert-small
        type: albert
        costs:
          prompt_tokens: 1
          completion_tokens: 3
        args:
          api_url: https://albert.api.etalab.gouv.fr
          api_key: ${ALBERT_API_KEY}
          timeout: 60

  - id: embeddings-small
    type: text-embeddings-inference
    aliases: ["BAAI/bge-m3"]
    clients:
      - model: embeddings-small
        type: albert
        args:
          api_url: https://albert.api.staging.etalab.gouv.fr
          api_key: ${ALBERT_API_KEY}
          timeout: 120

  - id: audio-large
    type: automatic-speech-recognition
    aliases: ["openai/whisper-large-v3"]
    clients: 
      - model: audio-large
        type: albert
        args:
          api_url: https://albert.api.staging.etalab.gouv.fr
          api_key: ${ALBERT_API_KEY}
          timeout: 120

  - id: rerank-small
    type: text-classification
    aliases: ["BAAI/bge-reranker-v2-m3"]
    clients:
      - model: rerank-small
        type: albert
        args:
          api_url: https://albert.api.staging.etalab.gouv.fr
          api_key: ${ALBERT_API_KEY}
          timeout: 120
