services:
  fastapi:
    image: ghcr.io/etalab-ia/albert-api/app:latest
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    environment:
      - CONFIG_FILE=/home/albert/conf/config.yml
    restart: always
    ports:
      - 8000:8000
    volumes:
     - .:/home/albert/conf
    depends_on:
      elastic:
        condition: service_healthy
      redis:
        condition: service_healthy

  streamlit:
    image: ghcr.io/etalab-ia/albert-api/ui:latest
    command: streamlit run ui/main.py --server.port=8501 --browser.gatherUsageStats false --theme.base=light --theme.primaryColor=#6a6af4 --server.maxUploadSize=20
    restart: always
    environment:
      - BASE_URL=http://fastapi:8000/v1
    ports:
      - 8501:8501

  redis:
    image: redis/redis-stack-server:7.2.0-v11
    restart: always
    environment:
      REDIS_ARGS: --dir /data --requirepass changeme --user username on >password ~* allcommands --save 60 1 --appendonly yes
    volumes:
      - redis:/data
    healthcheck:
        test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
        interval: 4s
        timeout: 10s
        retries: 5

  qdrant:
    image: qdrant/qdrant:v1.11.5-unprivileged
    restart: always
    environment:
      - QDRANT__SERVICE__API_KEY=changeme
    ports: 
      - 6333:6333
      - 6334:6334
    volumes:
      - qdrant:/qdrant/storage

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.0
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=elastic
      - logger.level=WARN
      - rootLogger.level=WARN
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health?wait_for_status=yellow"]
      interval: 10s
      timeout: 10s
      retries: 3

volumes:
  elasticsearch:
  qdrant:
  redis:
