services:
  fastapi:
    image: ghcr.io/etalab-ia/albert-api/app:latest
    command: gunicorn app.main:app --workers 1 --worker-connections 1000 --timeout 30 --worker-class uvicorn.workers.UvicornWorker
    environment:
      - TZ=Europe/Paris
      - PORT=8000
      - CONFIG_FILE=/home/albert/conf/config.yml
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./config.example.yml:/home/albert/conf/config.yml:ro
    depends_on:
      redis:
        condition: service_healthy

  streamlit:
    image: ghcr.io/etalab-ia/albert-api/ui:latest
    command: streamlit run ui/main.py --server.port=8501 --browser.gatherUsageStats false --theme.base=light --theme.primaryColor=#6a6af4 --server.maxUploadSize=20
    restart: always
    environment:
      - BASE_URL=http://fastapi:8000/v1
    ports:
      - 8501:8501

  redis:
    image: redis/redis-stack-server:7.2.0-v11
    restart: always
    environment:
      REDIS_ARGS: --dir /data --requirepass changeme --user username on >password ~* allcommands --save 60 1 --appendonly yes
    volumes:
      - redis:/data
    healthcheck:
        test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
        interval: 4s
        timeout: 10s
        retries: 5

  qdrant:
    image: qdrant/qdrant:v1.11.5-unprivileged
    restart: always
    environment:
      - QDRANT__SERVICE__API_KEY=changeme
    volumes:
      - qdrant:/qdrant/storage

volumes:
  qdrant:
  redis:
