name: albert-api

services:
  api:
    build:
      context: .
      dockerfile: app/Dockerfile
    platform: linux/amd64
    restart: always
    environment:
      - COVERAGE_RCFILE=./app/.coveragerc
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
      - QDRANT_HOST=qdrant
      - OPENAI_API_KEY=${OPENAI_API_KEY} # replace with your own key
    ports:
      - 8000:8000
    volumes:
      - ./config.yml:/config.yml:ro
    develop:
      watch:
        - action: sync+restart
          path: ./app
          target: /app
        - action: build+restart
          path: .
          target: /app
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      qdrant:
        condition: service_healthy

  playground:
    build:
      context: .
      dockerfile: ui/Dockerfile
    platform: linux/amd64
    restart: always
    ports:
      - 8501:8501
    environment:
      - API_HOST=api
      - POSTGRES_HOST=postgres
    volumes:
      - ./config.yml:/config.yml:ro
    develop:
      watch:
        - action: sync+restart
          path: ./ui
          target: /app
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    extends:
      file: compose.yml
      service: postgres

  redis:
    extends:
      file: compose.yml
      service: redis

  qdrant:
    extends:
      file: compose.yml
      service: qdrant

volumes:
  postgres:
  redis:
  qdrant:
