name: albert-api

services:
# quickstart services --------------------------------------------------------------------------------------------------------------------------------
  api:
    image: ghcr.io/etalab-ia/albert-api/app:latest
    restart: always
    env_file: "${APP_ENV_FILE:-./.env.example}"
    environment:
      - "CONFIG_FILE=config.yml" # inside the container, do not change this line
    ports:
      - 8080:8000
    volumes:
      - "${CONFIG_FILE:-./config.example.yml}:/config.yml:ro" # outside the container, do not change this line
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy

  playground:
    image: ghcr.io/etalab-ia/albert-api/ui:latest
    env_file: "${APP_ENV_FILE:-./.env.example}"
    environment:
      - "API_HOST=${API_HOST:-api}"
      - "POSTGRES_HOST=${POSTGRES_HOST:-postgres}"
      - "POSTGRES_PORT=${POSTGRES_PORT:-5432}"
    ports:
      - 8081:8501
    volumes:
      - "./${CONFIG_FILE:-config.example.yml}:/config.yml:ro"

  postgres:
    image: postgres:16.5
    restart: always
    env_file: "${APP_ENV_FILE:-./.env.example}"
    user: postgres
    environment:
      - "CREATE_DB=api,playground"
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./scripts/postgres_entrypoint.sh:/docker-entrypoint-initdb.d/postgres_entrypoint.sh
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "postgres" ]
      interval: 4s
      timeout: 10s
      retries: 5
      start_period: 60s

  redis:
    image: redis/redis-stack-server:7.2.0-v11
    restart: always
    env_file: "${APP_ENV_FILE:-./.env.example}"
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 4s
      timeout: 10s
      retries: 5

# additional services --------------------------------------------------------------------------------------------------------------------------------
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.2
    restart: always
    env_file: "${APP_ENV_FILE:-./.env.example}"
    ports:
      - "${ELASTICSEARCH_PORT:-9200}:9200"
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    healthcheck:
      test: [ "CMD-SHELL", "bash", "-c", ":> /dev/tcp/127.0.0.1/9200" ]
      interval: 4s
      timeout: 10s
      retries: 5

  qdrant:
   image: qdrant/qdrant:v1.11.5-unprivileged
   restart: always
   env_file: "${APP_ENV_FILE:-./.env.example}"
   volumes:
     - qdrant:/qdrant/storage
   ports:
     - "${QDRANT_PORT:-6333}:6333"
   healthcheck:
     test: [ "CMD-SHELL", "bash", "-c", ":> /dev/tcp/127.0.0.1/6333" ]
     interval: 4s
     timeout: 10s
     retries: 5

  marker:
    image: ghcr.io/etalab-ia/albert-marker/server:latest
    restart: always
    env_file: "${APP_ENV_FILE:-./.env.example}"
    ports:
      - "${MARKER_PORT:-9876}:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  secretiveshell:
    image: ghcr.io/etalab-ia/albert-api-mcp-bridge/albert-api-mcp-bridge:latest
    env_file: "${APP_ENV_FILE:-./.env.example}"
    restart: always
    ports:
      - "${SECRETIVESHELL_PORT:-8000}:8000"
    environment:
      - MCP_BRIDGE__CONFIG__FILE=config.json
    volumes:
      - ./mcp/config.json:/mcp_bridge/config.json

  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    ports:
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: master
      RABBITMQ_DEFAULT_PASS: changeme
    volumes:
      - rabbitmq:/var/lib/rabbitmq

volumes:
  elasticsearch:
  qdrant:
  postgres:
  redis:
  rabbitmq: