services:
  api:
    build:
      context: .
      dockerfile: app/Dockerfile
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./config.yml:/config.yml:ro
    develop:
      watch:
        - action: sync+restart
          path: ./app
          target: /app
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy

  playground:
    build:
      context: .
      dockerfile: ui/Dockerfile
    restart: always
    ports:
      - 8501:8501
    volumes:
      - ./config.yml:/config.yml:ro
    develop:
      watch:
        - action: sync+restart
          path: ./ui
          target: /app
    depends_on:
      postgres:
        condition: service_healthy


  postgres-ci:
    extends:
      file: compose.yml
      service: postgres

  redis-ci:
    extends:
      file: compose.yml
      service: redis

  qdrant-ci:
    extends:
      file: compose.yml
      service: qdrant
