services:
  api:
    image: ghcr.io/etalab-ia/albert-api/app:latest
    platform: linux/amd64
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./config.yml:/config.yml:ro
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy

  playground:
    image: ghcr.io/etalab-ia/albert-api/ui:latest
    platform: linux/amd64
    restart: always
    ports:
      - 8501:8501
    volumes:
      - ./config.yml:/config.yml:ro
    depends_on:
      postgres:
        condition: service_healthy

  redis:
    image: redis/redis-stack-server:7.2.0-v11
    restart: always
    environment:
      REDIS_ARGS: --dir /data --requirepass changeme --user username on >password ~* allcommands --save 60 1 --appendonly yes
    volumes:
      - redis:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 4s
      timeout: 10s
      retries: 5

  qdrant:
    image: qdrant/qdrant:v1.11.5-unprivileged
    restart: always
    environment:
      - QDRANT__SERVICE__API_KEY=changeme
    volumes:
      - qdrant:/qdrant/storage

  postgres:
    image: postgres:16.5
    restart: always
    user: postgres
    environment:
      - CREATE_DB=api,playground
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./scripts/postgres_entrypoint.sh:/docker-entrypoint-initdb.d/postgres_entrypoint.sh
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "postgres" ]
      interval: 4s
      timeout: 10s
      retries: 5
      start_period: 60s

volumes:
  qdrant:
  redis:
  postgres:
