models:
  - id: turbo
    type: text-generation
    default_internet: True
    clients:
      - model: gpt-3.5-turbo
        type: openai
        args:
          api_url: https://api.openai.com
          api_key: sk-...aB
          timeout: 60

  - id: embeddings-small
    type: text-embeddings-inference
    default_internet: True
    clients:
      - model: text-embedding-3-small
        type: openai
        args:
          api_url: https://api.openai.com
          api_key: sk-...aB
          timeout: 60

  - type: qdrant
    args:
      url: http://qdrant
      api_key: changeme
      prefer_grpc: True
      timeout: 10

  - type: redis
    args:
      host: redis
      password: changeme
  
  - type: sql
    args:
      url: postgresql://postgres:changeme@postgres:5432/postgres
