general:
  log_level: DEBUG

playground:
  api_url: http://${API_HOST}:8000
  max_api_key_expiration_days: 365
  cache_ttl: 1800 # seconds
  database_url: postgresql://postgres:changeme@${POSTGRES_HOST}:5432/playground

auth:
  master_username: master
  master_key: changeme

databases:
  - type: qdrant
    model: my-embeddings-model
    args:
      url: http://${QDRANT_HOST}
      api_key: changeme
      timeout: 10

  - type: redis
    args:
      host: ${REDIS_HOST}
      password: changeme

  - type: sql
    args:
      url: postgresql+asyncpg://postgres:changeme@${POSTGRES_HOST}:5432/api
      echo: False
      pool_size: 5
      max_overflow: 10
      pool_pre_ping: True
      connect_args: {"server_settings": {"statement_timeout": "120s"}}

models:
  - id: my-language-model
    type: text-generation
    clients:
      - model: gpt-3.5-turbo
        type: openai
        args:
          api_url: https://api.openai.com
          api_key: ${OPENAI_API_KEY}
          timeout: 60

  - id: my-embeddings-model
    type: text-embeddings-inference
    clients:
      - model: text-embedding-3-small
        type: openai
        args:
          api_url: https://api.openai.com
          api_key: ${OPENAI_API_KEY}
          timeout: 60
