models:
    - url: https://api.openai.com/v1
      type: text-generation

    - url: https://api.openai.com/v1
      type: text-embeddings-inference
      key: mysecretkey

    - url: https://api.openai.com/v1
      type: automatic-speech-recognition
      key: mysecretkey

databases:
  vectors:
    type: qdrant
    args:
      url: qdrant
      api_key: changeme
      prefer_grpc: True

  cache:
    type: redis
    args:
      host: redis
      password: changeme

