models:
    - url: https://api.openai.com/v1
      type: text-generation
      key: mysecretkey1
      search_internet: True

databases:
  vectors:
    type: qdrant
    args:
      url: qdrant
      api_key: changeme
      prefer_grpc: True

  cache:
    type: redis
    args:
      host: redis
      password: changeme

  files:
    type: minio
    args:
      endpoint_url: minio
      aws_access_key_id: minio
      aws_secret_access_key: changeme
