general:
  log_level: DEBUG
  # disabled_routers:
  #   - ocr


playground:
  api_url: http://${API_HOST}:8000

auth:
  master_username: master
  master_key: changeme

monitoring:
  postgres:
    enabled: true

mcp:
  mcp_bridge_url: http://localhost:9000/

databases:
  - type: qdrant
    context: api
    model: my-embeddings-model
    args:
      url: http://${QDRANT_HOST}
      api_key: changeme
      timeout: 10

  - type: redis
    context: api
    args:
      host: ${REDIS_HOST}
      password: changeme

  - type: sql # API database (async)
    context: api
    args:
      url: postgresql+asyncpg://postgres:changeme@${POSTGRES_HOST}:5432/api
      echo: False
      pool_size: 5
      max_overflow: 10
      pool_pre_ping: True
      connect_args:
        server_settings:
          statement_timeout: "120s"

  - type: sql # Playground database (sync)
    context: playground
    args:
      url: postgresql://postgres:changeme@${POSTGRES_HOST}:5432/playground
      echo: False
      pool_size: 5
      max_overflow: 10
      pool_pre_ping: True

models:
  - id: my-language-model
    type: text-generation
    clients:
      - model: gpt-3.5-turbo
        type: openai
        params:
          total: 70
          active: 70
          zone: WOR
        args:
          api_url: https://api.openai.com
          api_key: ${OPENAI_API_KEY}
          timeout: 60

  - id: my-embeddings-model
    type: text-embeddings-inference
    clients:
      - model: text-embedding-3-small
        type: openai
        args:
          api_url: https://api.openai.com
          api_key: ${OPENAI_API_KEY}
          timeout: 60
