# -------------------------------- dependencies ---------------------------------
dependencies:
  postgres: # required
    url: postgresql+asyncpg://postgres:${POSTGRES_PASSWORD:-changeme}@${POSTGRES_HOST:-postgres}:${POSTGRES_PORT:-5432}/postgres
    echo: False
    pool_size: 5
    connect_args:
      server_settings:
        statement_timeout: "120s"
      command_timeout: 60

  redis: # required
    url: redis://:${REDIS_PASSWORD:-changeme}@${REDIS_HOST:-redis}:${REDIS_PORT:-6379}
    max_connections: 200
    socket_connect_timeout: 5
    retry_on_timeout: True
    health_check_interval: 30
    decode_responses: False
    socket_keepalive: True
  

  # sentry:
  #   dsn: ${SENTRY_DSN}

  # langfuse:
  #   public_key: ${LANGFUSE_PUBLIC_KEY}
  #   secret_key: ${LANGFUSE_SECRET_KEY}
  #   base_url: http://localhost:3000

# ---------------------------------- settings -----------------------------------
settings:
  # disabled_routers: ["admin", "audio"]
  # hidden_routers: ["auth"]
  # usage_tokenizer: tiktoken_gpt2
  # app_title: My OpenGateLLM API

  # log_level: INFO
  # log_format: [%(asctime)s][%(process)d:%(name)s][%(levelname)s] %(client_ip)s - %(message)s

  swagger_version: 0.4.9
  # swagger_contact_url: https://github.com/etalab-ia/OpenGateLLM
  # swagger_contact_email: john.doe@example.com
  # swagger_docs_url: /docs
  # swagger_redoc_url: /redoc

  auth_secret_key: changeme
  auth_bootsrap_admin_username: admin
  auth_bootsrap_admin_password: changeme

  # rate_limiting_strategy: fixed_window

  # monitoring_sentry_enabled: True
  # monitoring_postgres_enabled: True
  # monitoring_prometheus_enabled: True

  playground_opengatellm_url: ${OPENGATELLM_URL:-http://api:8000}
  # playground_opengatellm_timeout: 60
  # playground_disabled_pages: []
  # playground_default_model: my-model
  # playground_theme_has_background: True
  # playground_theme_accent_color: purple
  # playground_theme_appearance: dark
  # playground_theme_gray_color: gray
  # playground_theme_panel_background: solid
  # playground_theme_radius: medium
  # playground_theme_scaling: 100%
  # playground_swagger_url: http://localhost:8000/swagger
  # playground_reference_url: http://localhost:8000/redoc
  # playground_documentation_url: https://docs.opengatellm.org

# ----------------------------------- models ------------------------------------
# models:
#   - name: albert-testbed
#     type: text-generation
#     # aliases: ["model-alias"]
#     # owned_by: Me
#     # load_balancing_strategy: shuffle
#     # cost_prompt_tokens: 0.10
#     # cost_completion_tokens: 0.10
#     providers:
#       - type: vllm
#         url: http://albert-testbed.etalab.gouv.fr:8000
#         # key: sk-xxx
#         model_name: "gemma3:1b"
#         # timeout: 60
#         # model_hosting_zone: FRA
#         # model_total_params: 8
#         # model_active_params: 8