models:
  - url: https://api.openai.com/v1
    type: text-generation

  - url: https://api.openai.com/v1
    type: text-embeddings-inference
    key: mysecretkey

  - url: https://api.openai.com/v1
    type: automatic-speech-recognition
    key: mysecretkey

internet:
  method: brave
  api_key: changeme

databases:
  search:
    type: qdrant
    args:
      url: qdrant
      api_key: changeme
      prefer_grpc: True
      timeout: 10

  cache:
    type: redis
    args:
      host: http://redis
      password: changeme

