general:
  log_level: DEBUG

playground:
  api_url: http://${API_HOST}:8000
  cache_ttl: 1800 # seconds

auth:
  master_username: master
  master_key: changeme
  # limiting_strategy: fixed_window
  # max_api_key_expiration_days: 365

# web_search:
#   - type: duckduckgo
#     model: my-language-model
#     limited_domains:
#       - google.com
#       - youtube.com
#     user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

# monitoring:
#   usage:
#     routers:
#       - all
#     tokenizer: tiktoken_o200k_base
#   sentry:
#     dsn: https://${SENTRY_DSN}
#   prometheus: true

databases:
  - type: qdrant
    context: api
    model: my-embeddings-model
    args:
      url: http://${QDRANT_HOST}
      api_key: changeme
      timeout: 10

  - type: redis
    context: api
    args:
      host: ${REDIS_HOST}
      password: changeme

  - type: sql # API database (async)
    context: api
    args:
      url: postgresql+asyncpg://postgres:changeme@${POSTGRES_HOST}:5432/api
      echo: False
      pool_size: 5
      max_overflow: 10
      pool_pre_ping: True
      connect_args:
        server_settings:
          statement_timeout: "120s"

  - type: sql # Playground database (sync)
    context: playground
    args:
      url: postgresql://postgres:changeme@${POSTGRES_HOST}:5432/playground
      echo: False
      pool_size: 5
      max_overflow: 10
      pool_pre_ping: True

models:
  - id: my-language-model
    type: text-generation
    clients:
      - model: gpt-3.5-turbo
        type: openai
        args:
          api_url: https://api.openai.com
          api_key: ${OPENAI_API_KEY}
          timeout: 60

  - id: my-embeddings-model
    type: text-embeddings-inference
    clients:
      - model: text-embedding-3-small
        type: openai
        args:
          api_url: https://api.openai.com
          api_key: ${OPENAI_API_KEY}
          timeout: 60
