general:
  log_level: DEBUG
  tokenizer: "tiktoken_gpt2"

playground:
  api_url: http://${API_HOST:-localhost}:8000
  max_api_key_expiration_days: 365
  cache_ttl: 1800
  database_url: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-changeme}@${POSTGRES_HOST:-localhost}:${POSTGRES_PORT:-5432}/playground

auth:
  master_username: master
  master_key: changeme

monitoring:
  postgres:
    enabled: true
  prometheus:
    enabled: true

mcp:
  mcp_bridge_url: http://${MCP_BRIDGE_HOST:-localhost}:${MCP_BRIDGE_PORT:-9876}

databases:
  - type: redis
    context: api
    args:
      host: ${REDIS_HOST:-localhost}
      port: ${REDIS_PORT:-6379}
      password: changeme

  - type: sql # API database (async)
    context: api
    args:
      url: postgresql+asyncpg://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-changeme}@${POSTGRES_HOST:-localhost}:${POSTGRES_PORT:-5432}/api
      echo: False
      pool_size: 10
      max_overflow: 5  # Allow some overflow connections
      pool_pre_ping: True
      pool_recycle: 3600  # Recycle connections after 1 hour
      pool_reset_on_return: commit  # Reset connection state on return
      connect_args:
        server_settings:
          statement_timeout: "120s"
        command_timeout: 60

  - type: sql # Playground database (sync)
    context: playground
    args:
      url: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-changeme}@${POSTGRES_HOST:-localhost}:${POSTGRES_PORT:-5432}/playground
      echo: False
      pool_size: 5
      max_overflow: 10
      pool_pre_ping: True

models:
  - id: 'albert-testbed'
    type: text-generation
    routing_strategy: round_robin
    aliases: ['gemma3:1b']
    clients:
      - model: 'gemma3:1b'
        type: vllm
        costs:
          prompt_tokens: 1
          completion_tokens: 3
        args:
          api_url: http://albert-testbed.etalab.gouv.fr:8000
          timeout: 60

#  - id: albert-large
#    type: image-text-to-text
#    owned_by: test
#    aliases: ["mistralai/Mistral-Small-3.1-24B-Instruct-2503"]
#    clients:
#      - model: albert-large
#        type: albert
#        costs:
#          prompt_tokens: 1
#          completion_tokens: 3
#        carbon:
#          total_params: 24
#          active_params: 24
#          model_zone: FRA
#        args:
#          api_url: ${ALBERT_API_URL:-https://albert.api.etalab.gouv.fr}
#          api_key: ${ALBERT_API_KEY}
#          timeout: 120
#
#  - id: ${EMBEDDINGS_MODEL:-embeddings-small}
#    type: text-embeddings-inference
#    aliases: ["BAAI/bge-m3"]
#    clients:
#      - model: ${EMBEDDINGS_MODEL:-embeddings-small}
#        type: albert
#        args:
#          api_url: ${ALBERT_API_URL:-https://albert.api.etalab.gouv.fr}
#          api_key: ${ALBERT_API_KEY}
#          timeout: 120
#
#  - id: audio-large
#    type: automatic-speech-recognition
#    aliases: ["openai/whisper-large-v3"]
#    clients:
#      - model: audio-large
#        type: albert
#        args:
#          api_url: ${ALBERT_API_URL:-https://albert.api.etalab.gouv.fr}
#          api_key: ${ALBERT_API_KEY}
#          timeout: 120
#
#  - id: rerank-small
#    type: text-classification
#    aliases: ["BAAI/bge-reranker-v2-m3"]
#    clients:
#      - model: rerank-small
#        type: albert
#        args:
#          api_url: ${ALBERT_API_URL:-https://albert.api.etalab.gouv.fr}
#          api_key: ${ALBERT_API_KEY}
#          timeout: 120