# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from __future__ import annotations

from typing_extensions import Literal, Required, TypedDict

from .._types import FileTypes

__all__ = ["AudioTranscribeParams"]


class AudioTranscribeParams(TypedDict, total=False):
    file: Required[FileTypes]
    """
    The audio file object (not file name) to transcribe, in one of these formats:
    mp3 or wav.
    """

    model: Required[str]
    """ID of the model to use.

    Call `/v1/models` endpoint to get the list of available models, only
    `automatic-speech-recognition` model type is supported.
    """

    language: Literal[
        "af",
        "afrikaans",
        "albanian",
        "am",
        "amharic",
        "ar",
        "arabic",
        "armenian",
        "as",
        "assamese",
        "az",
        "azerbaijani",
        "ba",
        "bashkir",
        "basque",
        "be",
        "belarusian",
        "bengali",
        "bg",
        "bn",
        "bo",
        "bosnian",
        "br",
        "breton",
        "bs",
        "bulgarian",
        "burmese",
        "ca",
        "cantonese",
        "castilian",
        "catalan",
        "chinese",
        "croatian",
        "cs",
        "cy",
        "czech",
        "da",
        "danish",
        "de",
        "dutch",
        "el",
        "en",
        "english",
        "es",
        "estonian",
        "et",
        "eu",
        "fa",
        "faroese",
        "fi",
        "finnish",
        "flemish",
        "fo",
        "fr",
        "french",
        "galician",
        "georgian",
        "german",
        "gl",
        "greek",
        "gu",
        "gujarati",
        "ha",
        "haitian",
        "haitian creole",
        "hausa",
        "haw",
        "hawaiian",
        "he",
        "hebrew",
        "hi",
        "hindi",
        "hr",
        "ht",
        "hu",
        "hungarian",
        "hy",
        "icelandic",
        "id",
        "indonesian",
        "is",
        "it",
        "italian",
        "ja",
        "japanese",
        "javanese",
        "jw",
        "ka",
        "kannada",
        "kazakh",
        "khmer",
        "kk",
        "km",
        "kn",
        "ko",
        "korean",
        "la",
        "lao",
        "latin",
        "latvian",
        "lb",
        "letzeburgesch",
        "lingala",
        "lithuanian",
        "ln",
        "lo",
        "lt",
        "luxembourgish",
        "lv",
        "macedonian",
        "malagasy",
        "malay",
        "malayalam",
        "maltese",
        "mandarin",
        "maori",
        "marathi",
        "mg",
        "mi",
        "mk",
        "ml",
        "mn",
        "moldavian",
        "moldovan",
        "mongolian",
        "mr",
        "ms",
        "mt",
        "my",
        "myanmar",
        "ne",
        "nepali",
        "nl",
        "nn",
        "no",
        "norwegian",
        "nynorsk",
        "oc",
        "occitan",
        "pa",
        "panjabi",
        "pashto",
        "persian",
        "pl",
        "polish",
        "portuguese",
        "ps",
        "pt",
        "punjabi",
        "pushto",
        "ro",
        "romanian",
        "ru",
        "russian",
        "sa",
        "sanskrit",
        "sd",
        "serbian",
        "shona",
        "si",
        "sindhi",
        "sinhala",
        "sinhalese",
        "sk",
        "sl",
        "slovak",
        "slovenian",
        "sn",
        "so",
        "somali",
        "spanish",
        "sq",
        "sr",
        "su",
        "sundanese",
        "sv",
        "sw",
        "swahili",
        "swedish",
        "ta",
        "tagalog",
        "tajik",
        "tamil",
        "tatar",
        "te",
        "telugu",
        "tg",
        "th",
        "thai",
        "tibetan",
        "tk",
        "tl",
        "tr",
        "tt",
        "turkish",
        "turkmen",
        "uk",
        "ukrainian",
        "ur",
        "urdu",
        "uz",
        "uzbek",
        "valencian",
        "vi",
        "vietnamese",
        "welsh",
        "yi",
        "yiddish",
        "yo",
        "yoruba",
        "yue",
        "zh",
        "",
    ]
    """The language of the output audio.

    If the output language is different than the audio language, the audio language
    will be translated into the output language. Supplying the output language in
    ISO-639-1 (e.g. en, fr) format will improve accuracy and latency.
    """

    prompt: str
    """An optional text to tell the model what to do with the input audio."""

    response_format: Literal["json", "text"]
    """The format of the transcript output, in one of these formats: `json` or `text`."""

    temperature: float
    """The sampling temperature, between 0 and 1.

    Higher values like 0.8 will make the output more random, while lower values like
    0.2 will make it more focused and deterministic. If set to 0, the model will use
    log probability to automatically increase the temperature until certain
    thresholds are hit.
    """
