# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from __future__ import annotations

from typing import Dict, Union, Iterable, Optional
from typing_extensions import Literal, Required, TypeAlias, TypedDict

from .._types import SequenceNotStr
from .search_method import SearchMethod

__all__ = ["ChatCreateCompletionParams", "SearchArgs"]


class ChatCreateCompletionParams(TypedDict, total=False):
    messages: Required[Iterable[object]]
    """A list of messages comprising the conversation so far."""

    model: Required[str]
    """ID of the model to use.

    Call `/v1/models` endpoint to get the list of available models, only
    `text-generation` model type is supported.
    """

    frequency_penalty: Optional[float]
    """Number between -2.0 and 2.0.

    Positive values penalize new tokens based on their existing frequency in the
    text so far, decreasing the model's likelihood to repeat the same line verbatim.
    """

    logit_bias: Optional[Dict[str, float]]
    """Modify the likelihood of specified tokens appearing in the completion.

    Accepts a JSON object that maps tokens (specified by their token ID in the
    tokenizer) to an associated bias value from -100 to 100. Mathematically, the
    bias is added to the logits generated by the model prior to sampling. The exact
    effect will vary per model, but values between -1 and 1 should decrease or
    increase likelihood of selection; values like -100 or 100 should result in a ban
    or exclusive selection of the relevant token.
    """

    logprobs: Optional[bool]
    """Whether to return log probabilities of the output tokens or not.

    If true, returns the log probabilities of each output token returned in the
    `content` of `message`.
    """

    max_completion_tokens: Optional[int]
    """An upper bound for the number of tokens that can be generated for a completion."""

    max_tokens: Optional[int]
    """The maximum number of tokens that can be generated in the chat completion.

    This value can be used to control costs for text generated via API.
    """

    n: Optional[int]
    """How many chat completion choices to generate for each input message.

    Note that you will be charged based on the number of generated tokens across all
    of the choices. Keep `n` as `1` to minimize costs.
    """

    parallel_tool_calls: Optional[bool]
    """Whether to call tools in parallel or sequentially.

    If true, the model will call tools in parallel. If false, the model will call
    tools sequentially. If None, the model will call tools in parallel if the model
    supports it, otherwise it will call tools sequentially.
    """

    presence_penalty: Optional[float]
    """Number between -2.0 and 2.0.

    Positive values penalize new tokens based on whether they appear in the text so
    far, increasing the model's likelihood to talk about new topics.
    """

    response_format: object
    """
    Setting to `{ "type": "json_schema", "json_schema": {...} }` enables Structured
    Outputs which ensures the model will match your supplied JSON schema. Learn more
    in the Structured Outputs guide. Setting to `{ "type": "json_object" }` enables
    JSON mode, which ensures the message the model generates is valid JSON.
    **Important**: when using JSON mode, you must also instruct the model to produce
    JSON yourself via a system or user message. Without this, the model may generate
    an unending stream of whitespace until the generation reaches the token limit,
    resulting in a long-running and seemingly "stuck" request. Also note that the
    message content may be partially cut off if `finish_reason="length"`, which
    indicates the generation exceeded `max_tokens` or the conversation exceeded the
    max context length.
    """

    search: bool

    search_args: Optional[SearchArgs]

    seed: Optional[int]
    """
    If specified, our system will make a best effort to sample deterministically,
    such that repeated requests with the same `seed` and parameters should return
    the same result. Determinism is not guaranteed, and you should refer to the
    system_fingerprint response parameter to monitor changes in the backend.
    """

    stop: Union[str, SequenceNotStr[str], None]
    """Up to 4 sequences where the API will stop generating further tokens."""

    stream: Optional[Literal[True, False]]
    """If set, partial message deltas will be sent.

    Tokens will be sent as data-only server-sent events as they become available,
    with the stream terminated by a data: [DONE] message.
    """

    stream_options: object
    """Options for streaming response. Only set this when you set `stream: true`."""

    temperature: Optional[float]
    """What sampling temperature to use, between 0 and 2.

    Higher values like 0.8 will make the output more random, while lower values like
    0.2 will make it more focused and deterministic. We generally recommend altering
    this or `top_p` but not both.
    """

    tool_choice: object
    """Controls which (if any) tool is called by the model.

    `none` means the model will not call any tool and instead generates a message.
    `auto` means the model can pick between generating a message or calling one or
    more tools. `required` means the model must call one or more tools. Specifying a
    particular tool via `{"type": "function", "function": {"name": "my_function"}}`
    forces the model to call that tool. `none` is the default when no tools are
    present. `auto` is the default if tools are present.
    """

    tools: Optional[Iterable[object]]
    """A list of tools the model may call.

    Currently, only functions are supported as a tool. Use this to provide a list of
    functions the model may generate JSON inputs for.
    """

    top_logprobs: Optional[int]
    """
    An integer between 0 and 20 specifying the number of most likely tokens to
    return at each token position, each with an associated log probability.
    `logprobs` must be set to `true` if this parameter is used.
    """

    top_p: Optional[float]
    """
    An alternative to sampling with temperature, called nucleus sampling, where the
    model considers the results of the tokens with top_p probability mass. So 0.1
    means only the tokens comprising the top 10% probability mass are considered. We
    generally recommend altering this or `temperature` but not both.
    """

    user: Optional[str]
    """A unique identifier representing the user."""


class SearchArgsTyped(TypedDict, total=False):
    collections: Required[Iterable[int]]
    """List of collections ID"""

    k: int
    """[DEPRECATED: use limit instead]Number of results to return.

    A large number of results will increase the model context size and hence the
    response time.
    """

    limit: int
    """Number of results to return"""

    method: SearchMethod
    """Search method to use"""

    offset: int
    """Offset for pagination, specifying how many results to skip from the beginning"""

    rff_k: int
    """
    Smoothing constant for Reciprocal Rank Fusion (RRF) algorithm in hybrid search
    (recommended: from 10 to 100).
    """

    score_threshold: float
    """
    Score of cosine similarity threshold for filtering results, only available for
    semantic search method.
    """

    template: str
    """Template to use for the RAG query.

    The template must contain "{chunks}" and "{prompt}" placeholders.
    """


SearchArgs: TypeAlias = Union[SearchArgsTyped, Dict[str, object]]
