{
 "title": "Traffic",
 "description": "FastAPI dashboard for programs using FastAPI instrumented via prometheus_fastapi_instrumentator",
 "time": { "from": "now-1d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "app_name",
    "label": "Application Name",
    "query": {
     "query": "label_values(ogl_http_requests_total,job)"
    }
   },
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 12, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ogl_http_requests_total{job=\"$app_name\", handler!=\"/metrics\"})"
    }
   ]
  },
  {
   "title": "Requests Count",
   "type": "stat",
   "gridPos": { "h": 12, "w": 7, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ogl_http_requests_total{job=\"$app_name\", handler!=\"/metrics\"}",
     "legendFormat": "{{method}} {{handler}}"
    }
   ]
  },
  {
   "title": "Requests Average Duration",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 13, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by(handler, method) (ogl_http_request_duration_seconds_sum{job=\"$app_name\", handler!=\"none\", handler!=\"/metrics\", method!~\"HEAD|OPTIONS\", status!~\"3..\"}) / sum by(handler, method) (ogl_http_request_duration_seconds_count{job=\"$app_name\", handler!=\"none\", handler!=\"/metrics\", method!~\"HEAD|OPTIONS\", status!~\"3..\"}))",
     "legendFormat": "{{method}} {{handler}}"
    }
   ]
  },
  {
   "title": "Percent of 2xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(handler, method) (ogl_http_requests_total{job=\"$app_name\", status=~\"2.*\", handler!=\"/metrics\"}) / sum by(handler, method) (ogl_http_requests_total{job=\"$app_name\", handler!=\"/metrics\"})",
     "legendFormat": "{{method}} {{handler}}"
    }
   ]
  },
  {
   "title": "Percent of 5xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(handler, method) (ogl_http_requests_total{job=\"$app_name\", status=~\"5.*\", handler!=\"/metrics\"}) / sum by(handler, method) (ogl_http_requests_total{job=\"$app_name\", handler!=\"/metrics\"})",
     "legendFormat": "{{method}} {{handler}}"
    }
   ]
  },
  {
   "title": "PR 99 Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.99,sum(rate(ogl_http_request_duration_seconds_bucket{job=\"$app_name\", handler!=\"/metrics\"}[1m])) by(handler, method, le))",
     "legendFormat": "{{method}} {{handler}}"
    }
   ]
  },
  {
   "title": "Request time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
   "targets": [
    {
     "expr": "sum by(handler, method) (rate(ogl_http_request_duration_seconds_sum{job=\"$app_name\", handler!=\"none\", handler!=\"/metrics\", method!~\"HEAD|OPTIONS\", status!~\"3..\"}[1m])) / sum by(handler, method) (rate(ogl_http_request_duration_seconds_count{job=\"$app_name\", handler!=\"none\", handler!=\"/metrics\", method!~\"HEAD|OPTIONS\", status!~\"3..\"}[1m]))",
     "legendFormat": "{{method}} {{handler}}"
    }
   ]
  },
  {
   "title": "Request Per Sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(handler, method) (rate(ogl_http_requests_total{job=\"$app_name\", handler!=\"/metrics\"}[1m]))",
     "legendFormat": "{{method}} {{handler}}"
    }
   ]
  },
  {
   "title": "Python Process Resident Memory Use",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"$app_name\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Python Process CPU Use",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{job=\"$app_name\"}[5m])*10",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}