from typing import Annotated, Any, Literal

from openai.types.chat import ChatCompletion, ChatCompletionChunk
from pydantic import BeforeValidator, Field

from api.domain import BaseModel
from api.domain.search.entities import ChunkMetadata, ComparisonFilter, CompoundFilter, SearchMethod
from api.domain.usage.entities import Usage
from api.infrastructure.fastapi.schemas import UnixTimestamp


def _false_when_null(value: bool | None) -> bool:
    """OpenAI-compatible clients send `stream: null` to mean "not set"; the use case branches on a real bool."""
    return False if value is None else value


class SearchTool(BaseModel):
    type: Annotated[Literal["search"], Field(description="The type of the tool. Set to `search` to ground the completion on your collections.")]  # fmt: off
    collection_ids: Annotated[list[int], Field(default=[], min_length=0, max_length=100, description="List of collections ID to search in.")]  # fmt: off
    document_ids: Annotated[list[int], Field(default=[], min_length=0, max_length=100, description="List of document IDs to search in.")]  # fmt: off
    metadata_filters: Annotated[ComparisonFilter | CompoundFilter | None, Field(default=None, description="Metadata filters to apply to the search.")]  # fmt: off
    limit: Annotated[int, Field(gt=0, le=100, default=10, description="Number of results to return.")]
    offset: Annotated[int, Field(ge=0, default=0, description="Offset for pagination, specifying how many results to skip from the beginning.")]  # fmt: off
    method: Annotated[SearchMethod, Field(default=SearchMethod.SEMANTIC, description="Search method to use.")]
    rff_k: Annotated[int, Field(default=60, ge=0, le=16384, description="Smoothing constant for Reciprocal Rank Fusion (RRF) algorithm in hybrid search (recommended: from 10 to 100).")]  # fmt: off
    score_threshold: Annotated[float, Field(default=0.0, ge=0.0, le=1.0, description="Score of cosine similarity threshold for filtering results, only available for semantic search method.")]  # fmt: off


class CreateChatCompletionsBody(BaseModel):
    # only the union between OpenAI fields and vLLM fields is defined. See https://github.com/vllm-project/vllm/blob/main/vllm/entrypoints/openai/protocol.py#L209
    messages: Annotated[list[dict], Field(description="A list of messages comprising the conversation so far.")]  # fmt: off
    model: Annotated[str, Field(description="ID of the model to use. Call `/v1/models` endpoint to get the list of available models, only `text-generation` model type is supported.")]  # fmt: off
    frequency_penalty: Annotated[float | None, Field(default=0.0, description="Number between -2.0 and 2.0. Positive values penalize new tokens based on their existing frequency in the text so far, decreasing the model's likelihood to repeat the same line verbatim.")]  # fmt: off
    logit_bias: Annotated[dict[str, float] | None, Field(default=None, description="Modify the likelihood of specified tokens appearing in the completion. Accepts a JSON object that maps tokens (specified by their token ID in the tokenizer) to an associated bias value from -100 to 100. Mathematically, the bias is added to the logits generated by the model prior to sampling. The exact effect will vary per model, but values between -1 and 1 should decrease or increase likelihood of selection; values like -100 or 100 should result in a ban or exclusive selection of the relevant token.")]  # fmt: off
    logprobs: Annotated[bool | None, Field(default=False, description="Whether to return log probabilities of the output tokens or not. If true, returns the log probabilities of each output token returned in the `content` of `message`.")]  # fmt: off
    top_logprobs: Annotated[int | None, Field(default=None, description="An integer between 0 and 20 specifying the number of most likely tokens to return at each token position, each with an associated log probability. `logprobs` must be set to `true` if this parameter is used.")]  # fmt: off
    presence_penalty: Annotated[float | None, Field(default=0.0, description="Number between -2.0 and 2.0. Positive values penalize new tokens based on whether they appear in the text so far, increasing the model's likelihood to talk about new topics.")]  # fmt: off
    max_completion_tokens: Annotated[int | None, Field(default=None, description="An upper bound for the number of tokens that can be generated for a completion.")]  # fmt: off
    n: Annotated[int | None, Field(default=1, description="How many chat completion choices to generate for each input message. Note that you will be charged based on the number of generated tokens across all of the choices. Keep `n` as `1` to minimize costs.")]  # fmt: off
    response_format: Annotated[Any | None, Field(default=None, description="Setting to `{ \"type\": \"json_schema\", \"json_schema\": {...} }` enables Structured Outputs which ensures the model will match your supplied JSON schema. Learn more in the Structured Outputs guide. Setting to `{ \"type\": \"json_object\" }` enables JSON mode, which ensures the message the model generates is valid JSON.<br>**Important**: when using JSON mode, you must also instruct the model to produce JSON yourself via a system or user message. Without this, the model may generate an unending stream of whitespace until the generation reaches the token limit, resulting in a long-running and seemingly \"stuck\" request. Also note that the message content may be partially cut off if `finish_reason=\"length\"`, which indicates the generation exceeded `max_tokens` or the conversation exceeded the max context length.")]  # fmt: off
    seed: Annotated[int | None, Field(default=None, description="If specified, our system will make a best effort to sample deterministically, such that repeated requests with the same `seed` and parameters should return the same result. Determinism is not guaranteed, and you should refer to the system_fingerprint response parameter to monitor changes in the backend.")]  # fmt: off
    stop: Annotated[str | list[str] | None, Field(default_factory=list, description="Up to 4 sequences where the API will stop generating further tokens.")]  # fmt: off
    stream: Annotated[bool, BeforeValidator(_false_when_null), Field(default=False, description="If set, partial message deltas will be sent. Tokens will be sent as data-only server-sent events as they become available, with the stream terminated by a data: [DONE] message.")]  # fmt: off
    stream_options: Annotated[Any | None, Field(default=None, description="Options for streaming response. Only set this when you set `stream: true`.")]  # fmt: off
    temperature: Annotated[float | None, Field(default=None, description="What sampling temperature to use, between 0 and 2. Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic. We generally recommend altering this or `top_p` but not both.")]  # fmt: off
    top_p: Annotated[float | None, Field(default=None, description="An alternative to sampling with temperature, called nucleus sampling, where the model considers the results of the tokens with top_p probability mass. So 0.1 means only the tokens comprising the top 10% probability mass are considered.<br>We generally recommend altering this or `temperature` but not both.")]  # fmt: off
    tools: Annotated[list[SearchTool | dict] | None, Field(default=None, description="A list of tools the model may call. Functions are supported, plus the OpenGateLLM `search` tool that grounds the completion on your collections.")]  # fmt: off
    tool_choice: Annotated[Any, Field(default="none", description="Controls which (if any) tool is called by the model. `none` means the model will not call any tool and instead generates a message. `auto` means the model can pick between generating a message or calling one or more tools. `required` means the model must call one or more tools. Specifying a particular tool via `{\"type\": \"function\", \"function\": {\"name\": \"my_function\"}}` forces the model to call that tool.<br>`none` is the default when no tools are present. `auto` is the default if tools are present.")]  # fmt: off
    parallel_tool_calls: Annotated[bool | None, Field(default=False, description="Whether to call tools in parallel or sequentially. If true, the model will call tools in parallel. If false, the model will call tools sequentially. If None, the model will call tools in parallel if the model supports it, otherwise it will call tools sequentially.")]  # fmt: off
    user: Annotated[str | None, Field(default=None, description="A unique identifier representing the user.")]  # fmt: off


class ChunkResponse(BaseModel):
    object: Annotated[Literal["chunk"], Field(default="chunk", description="The type of the object.")]
    id: Annotated[int, Field(description="A unique identifier for the chunk.")]
    collection_id: Annotated[int, Field(description="The collection the chunk belongs to.")]
    document_id: Annotated[int, Field(description="The document the chunk belongs to.")]
    content: Annotated[str, Field(description="The chunk content used to ground the completion.")]
    metadata: Annotated[ChunkMetadata | None, Field(default=None, description="The chunk metadata.")]
    created: Annotated[UnixTimestamp, Field(description="Time of creation, as Unix timestamp.")]


class SearchResponse(BaseModel):
    method: Annotated[SearchMethod, Field(description="The search method that retrieved the chunk.")]
    score: Annotated[float, Field(description="The relevance score of the chunk for the query.")]
    chunk: Annotated[ChunkResponse, Field(description="The retrieved chunk.")]


class ChatCompletionResponse(ChatCompletion):
    id: Annotated[str | None, Field(default=None, description="A unique identifier for the chat completion.")]
    usage: Annotated[Usage, Field(default_factory=Usage, description="Usage information for the request.")]
    search_results: Annotated[list[SearchResponse] | None, Field(default=None, description="Chunks retrieved by the search tool, null when the tool was not requested.")]  # fmt: off


class ChatCompletionChunkResponse(ChatCompletionChunk):
    usage: Annotated[Usage | None, Field(default=None, description="Usage information, sent on the last chunk of the stream.")]
    search_results: Annotated[list[SearchResponse] | None, Field(default=None, description="Chunks retrieved by the search tool, sent on the last chunk of the stream.")]  # fmt: off
