apiVersion: v1
kind: Service
metadata:
  name: qdrant
  namespace: default
spec:
  selector:
    app: qdrant
  ports:
    - name: grpc
      port: 6334
      targetPort: 6334  # gRPC port
    - name: http
      port: 6333
      targetPort: 6333  # HTTP port
  type: ClusterIP