[theme]
# One of "light" or "dark".
base = "dark"

# Primary accent color for interactive elements.
primaryColor = "#6a6af4"

# Background color for the main content area.
backgroundColor = "#161616"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#1e1e1e"

# Color used for almost all text.
textColor = "#f6f6f6"

# Font family for all text in the app, except code blocks. One of "sans serif",
# "serif", or "monospace".
font = "sans serif"
